name: nvh-software
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - annotated-types=0.7.0=pyhd8ed1ab_1
  - appdirs=1.4.4=pyhd8ed1ab_1
  - backports=1.0=pyhd8ed1ab_5
  - backports.tarfile=1.2.0=pyhd8ed1ab_1
  - brotli-python=1.0.9=py311h313beb8_9
  - bzip2=1.0.8=h99b78c6_7
  - ca-certificates=2024.12.31=hca03da5_0
  - cachecontrol=0.14.2=pyha770c72_0
  - cachecontrol-with-filecache=0.14.2=pyhd8ed1ab_0
  - cachy=0.3.0=pyhd8ed1ab_2
  - certifi=2024.12.14=pyhd8ed1ab_0
  - charset-normalizer=3.4.1=pyhd8ed1ab_0
  - click=8.1.8=pyh707e725_0
  - click-default-group=1.2.4=pyhd8ed1ab_1
  - clikit=0.6.2=pyhd8ed1ab_3
  - conda-lock=2.5.7=pyhd8ed1ab_1
  - crashtest=0.4.1=pyhd8ed1ab_1
  - distlib=0.3.9=pyhd8ed1ab_1
  - ensureconda=1.4.4=pyhd8ed1ab_1
  - filelock=3.16.1=pyhd8ed1ab_1
  - gitdb=4.0.12=pyhd8ed1ab_0
  - gitpython=3.1.44=pyhff2d567_0
  - html5lib=1.1=pyhd8ed1ab_2
  - idna=3.10=pyhd8ed1ab_1
  - importlib-metadata=8.5.0=pyha770c72_1
  - importlib_resources=6.5.2=pyhd8ed1ab_0
  - jaraco.classes=3.4.0=pyhd8ed1ab_2
  - jaraco.context=6.0.1=pyhd8ed1ab_0
  - jaraco.functools=4.1.0=pyhd8ed1ab_0
  - jinja2=3.1.5=pyhd8ed1ab_0
  - keyring=25.6.0=pyh534df25_0
  - libcxx=19.1.6=ha82da77_1
  - libffi=3.4.4=hca03da5_1
  - libsqlite=3.45.3=h091b4b1_0
  - libzlib=1.2.13=hfb2fe0b_6
  - markupsafe=3.0.2=pyhe1237c8_1
  - more-itertools=10.5.0=pyhd8ed1ab_1
  - msgpack-python=1.0.3=py311h48ca7d4_0
  - ncurses=6.4.20240210=h078ce10_0
  - openssl=3.4.0=h81ee809_1
  - packaging=24.2=pyhd8ed1ab_2
  - pastel=0.2.1=pyhd8ed1ab_0
  - pip=24.2=pyh8b19718_1
  - pkginfo=1.12.0=pyhd8ed1ab_1
  - platformdirs=4.3.6=pyhd8ed1ab_1
  - pylev=1.4.0=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.11.11=hb885b13_0
  - pyyaml=6.0.2=pyhe1237c8_2
  - readline=8.2=h92ec313_1
  - requests=2.32.3=pyhd8ed1ab_1
  - ruamel.yaml=0.18.6=py311h80987f9_0
  - ruamel.yaml.clib=0.2.8=py311h80987f9_0
  - setuptools=75.1.0=pyhd8ed1ab_0
  - six=1.17.0=pyhd8ed1ab_0
  - smmap=5.0.0=pyhd8ed1ab_0
  - sqlite=3.45.3=hf2abe2d_0
  - tk=8.6.14=h6ba3021_0
  - tomli=2.2.1=pyhd8ed1ab_1
  - tomlkit=0.13.2=pyha770c72_1
  - toolz=0.12.1=pyhd8ed1ab_0
  - typing-extensions=4.12.2=hd8ed1ab_1
  - typing_extensions=4.12.2=pyha770c72_1
  - urllib3=1.26.19=pyhd8ed1ab_0
  - virtualenv=20.28.1=pyhd8ed1ab_0
  - webencodings=0.5.1=pyhd8ed1ab_3
  - wheel=0.44.0=pyhd8ed1ab_0
  - xz=5.4.6=h80987f9_1
  - yaml=0.2.5=h3422bc3_2
  - zipp=3.21.0=pyhd8ed1ab_1
  - zlib=1.2.13=hfb2fe0b_6
  - pip:
      - aisuite==0.1.7
      - anyio==4.8.0
      - contourpy==1.3.1
      - cycler==0.12.1
      - distro==1.9.0
      - fonttools==4.55.3
      - h11==0.14.0
      - httpcore==1.0.7
      - httpx==0.27.2
      - jiter==0.8.2
      - kiwisolver==1.4.8
      - matplotlib==3.10.0
      - mplcursors==0.6
      - numpy==2.2.1
      - openai==1.59.6
      - pandas==2.2.3
      - pillow==11.1.0
      - pyaudio==0.2.14
      - pydantic==2.10.5
      - pydantic-core==2.27.2
      - pydub==0.25.1
      - pyoma-2==1.0.0
      - pyparsing==3.2.1
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.0.1
      - pytz==2024.2
      - scipy==1.15.1
      - sniffio==1.3.1
      - tqdm==4.67.1
      - tzdata==2025.1
prefix: /opt/homebrew/anaconda3/envs/nvh-software
