name: test_env
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - annotated-types=0.7.0
  - appdirs=1.4.4
  - backports=1.0
  - backports.tarfile=1.2.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2024.12.31
  - cachecontrol=0.14.2
  - cachecontrol-with-filecache=0.14.2
  - cachy=0.3.0
  - certifi=2024.12.14
  - charset-normalizer=3.4.1
  - click=8.1.8
  - click-default-group=1.2.4
  - clikit=0.6.2
  - conda-lock=2.5.7
  - crashtest=0.4.1
  - distlib=0.3.9
  - ensureconda=1.4.4
  - filelock=3.16.1
  - gitdb=4.0.12
  - gitpython=3.1.44
  - html5lib=1.1
  - idna=3.10
  - importlib-metadata=8.5.0
  - importlib_resources=6.5.2
  - jaraco.classes=3.4.0
  - jaraco.context=6.0.1
  - jaraco.functools=4.1.0
  - jinja2=3.1.5
  - keyring=25.6.0
  - libcxx=19.1.6
  - libffi=3.4.4
  - markupsafe=3.0.2
  - more-itertools=10.5.0
  - msgpack-python=1.0.3
  - ncurses=6.4
  - openssl=3.4.0
  - packaging=24.2
  - pastel=0.2.1
  - pip=24.2
  - pkginfo=1.12.0
  - platformdirs=4.3.6
  - pylev=1.4.0
  - pysocks=1.7.1
  - python=3.11.11
  - pyyaml=6.0.2
  - readline=8.2
  - requests=2.32.3
  - ruamel.yaml=0.18.6
  - ruamel.yaml.clib=0.2.8
  - setuptools=75.1.0
  - six=1.17.0
  - smmap=5.0.0
  - sqlite=3.45.3
  - tk=8.6.14
  - tomli=2.2.1
  - tomlkit=0.13.2
  - toolz=0.12.1
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - tzdata=2024b
  - urllib3=1.26.19
  - virtualenv=20.28.1
  - webencodings=0.5.1
  - wheel=0.44.0
  - xz=5.4.6
  - yaml=0.2.5
  - zipp=3.21.0
  - zlib=1.2.13
  - pip:
      - aisuite==0.1.7
      - anyio==4.8.0
      - contourpy==1.3.1
      - cycler==0.12.1
      - distro==1.9.0
      - fonttools==4.55.3
      - h11==0.14.0
      - httpcore==1.0.7
      - httpx==0.27.2
      - jiter==0.8.2
      - kiwisolver==1.4.8
      - matplotlib==3.10.0
      - numpy==2.2.1
      - openai==1.59.6
      - pillow==11.1.0
      - pyaudio==0.2.14
      - pydantic==2.10.5
      - pydantic-core==2.27.2
      - pydub==0.25.1
      - pyparsing==3.2.1
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.0.1
      - scipy==1.15.1
      - sniffio==1.3.1
      - tqdm==4.67.1
prefix: /Users/jiaqi/anaconda3/envs/test_env
